name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      
    - name: Setup Node
      uses: actions/setup-node@v1.4.2
      
    - name: Dotnet Restore
      run: dotnet restore MHC_ASPNetCore.sln
      
    - name: NPM Install Bower
      run: npm install -g bower
      working-directory: 'src/MyHealth.Web'
      
    - name: NPM Install 
      run: npm install 
      working-directory: 'src/MyHealth.Web'
      
    - name: Install bower Packages
      run: bower install bower.json
      working-directory: 'src/MyHealth.Web/'
